---
- name: installing and launching filebeat
  hosts: webservers # #TODO# Should match your ansible/hosts file's web VM group.
  become: yes
  tasks:

    # #TODO# Check Elastic.co for most recent version.
  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    # #TODO# Should match the verion you downloaded above.
  - name: install filebeat deb
    command: dpkg -i filebeat-7.6.1-amd64.deb

    # #TODO# Make sure the src matches the location of your Filebeat config file.
  - name: drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat service
    command: service filebeat start

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes
